package com.coxandkings.travel.bookingengine.orchestrator.activities;

import java.time.format.DateTimeFormatter;

public interface ActivityService {
	public static final String PRODUCT = "SIGHTSEEING";
	public static final String NS_SIGHTSEEING = "http://www.coxandkings.com/integ/suppl/sightseeing";
	public static final String NS_OTA = "http://www.opentravel.org/OTA/2003/05";
	public static DateTimeFormatter mDateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
	public static DateTimeFormatter mDateTimeFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
	public static final String JSON_PROP_RESHEADER = "responseHeader";
	public static final String JSON_PROP_RESBODY = "responseBody";
	public static final String JSON_PROP_REQHEADER = "requestHeader";
	public static final String JSON_PROP_REQBODY = "requestBody";

	public static final String JSON_PROP_SESSIONID = "sessionID";
	public static final String JSON_PROP_TRANSACTID = "transactionID";
	public static final String JSON_PROP_USERID = "userID";

	public static final String SUPPLIER_ID = "supplierID";
	public static final String PRODUCT_SIGHTSEEING = "";

	public static final String PRODUCT_CATEGORY = "Activities";
	public static final String PRODUCT_SUBCATEGORY = "Tours & Sightseeing";

	public static final String JSON_PROP_COUNTRYCODE = "countryCode";
	public static final String JSON_PROP_CITYCODE = "cityCode";
	public static final String JSON_PROP_AMOUNT = "amount";
	public static final String JSON_PROP_CCYCODE = "currencyCode";
	public static final String JSON_PROP_PAXTYPE = "paxType";
	public static final String JSON_PROP_CONTACTDETAILS = "contactDetails";
	public static final String JSON_PROP_ADDRESS = "address";
	public static final String JSON_PROP_CTRYACESCODE = "countryAccessCode";
	public static final String JSON_PROP_EMAIL = "email";
	public static final String JSON_PROP_COUNTRYNAME = "countryName";
	public static final String JSON_PROP_BOOKREFID = "bookRefId";
	public static final String JSON_PROP_TYPE = "type";
	public static final String JSON_PROP_PRODUCT = "product";
	public static final String JSON_PROP_ACTIVITYINFO = "activityInfo";
	public static final String JSON_PROP_TOURACTIVITYINFO = "tourActivityInfo";
	public static final String JSON_PROP_SCHEDULE = "schedule";
	public static final String JSON_PROP_DETAILS = "details";
	public static final String JSON_PROP_DURATION = "duration";
	public static final String JSON_PROP_ENDDATE = "endDate";
	public static final String JSON_PROP_STARTDATE = "startDate";
	public static final String JSON_PROP_DESCRIPTION = "description";
	public static final String JSON_PROP_LONGDESCRIPTION = "longDescription";
	public static final String JSON_PROP_SHORTDESCRIPTION = "shortDescription";
	public static final String JSON_PROP_BASICINFO = "basicInfo";
	public static final String JSON_PROP_REFERENCE = "reference";
	public static final String JSON_PROP_RATEKEY = "rateKey";
	public static final String JSON_PROP_SUPPLIERPRODUCTCODE = "supplierProductCode";
	public static final String JSON_PROP_SUPPLIERBRANDCODE = "supplierBrandCode";
	public static final String JSON_PROP_AVAILABILITYSTATUS = "availabilty_status";
	public static final String JSON_PROP_PRICING = "pricing";
	public static final String JSON_PROP_PARTICIPANT = "participant";
	public static final String JSON_PROP_ALLOWINFANTS = "allowInfants";
	public static final String JSON_PROP_MINADULTAGE = "minAdultAge";
	public static final String JSON_PROP_MAXINFANTAGE = "maxInfantAge";
	public static final String JSON_PROP_ALLOWCHILDREN = "allowChildren";
	public static final String JSON_PROP_MININDIVIDUALS = "minIndividuals";
	public static final String JSON_PROP_MAXADULTAGE = "maxAdultAge";
	public static final String JSON_PROP_MAXCHILDAGE = "maxChildAge";
	public static final String JSON_PROP_MAXINDIVIDUALS = "maxIndividuals";
	public static final String JSON_PROP_MINCHILDAGE = "minChildAge";
	public static final String JSON_PROP_MININFANTAGE = "minInfantAge";
	public static final String JSON_PROP_SHIPPINGDETAILS = "shipping_Details";
	public static final String JSON_PROP_TOURLANGUAGE = "tourLanguage";
	public static final String JSON_PROP_NAME = "name";
	public static final String JSON_PROP_QUALIFIERINFO = "qualifierInfo";
	public static final String JSON_PROP_PERSONNAME = "personName";
	public static final String JSON_PROP_DOB = "DOB";
	public static final String JSON_PROP_SHIPPINGAREAS = "shippingAreas";
	public static final String JSON_PROP_AREAID = "areaID";
	public static final String JSON_PROP_RESERVATIONS = "reservations";
	public static final String JSON_PROP_ID = "ID";
	public static final String JSON_PROP_TOTALCOST = "totalCost";
	public static final String JSON_PROP_COMMERCIALNAME = "commercialName";
	public static final String JSON_PROP_COMMERCIALTYPE = "commercialType";
	public static final String JSON_PROP_COMMERCIALAMOUNT = "commercialAmount";
	public static final String JSON_PROP_MARKUPCOMMERCIALDETAILS = "markUpCommercialDetails";
	public static final String JSON_PROP_ENTITYNAME = "entityName";
	public static final String JSON_PROP_ENTITYCOMMERCIALS = "entityCommercials";
	public static final String JSON_PROP_CLIENTCOMMERCIALS = "clientCommercials";
	public static final String JSON_PROP_SUPPLIERCOMMERCIALS = "supplierCommercials";
	public static final String JSON_PROP_STARTTIME = "startTime";
	public static final String JSON_PROP_ENDTIME = "endTime";
	public static final String JSON_PROP_DAYS = "days";
	public static final String JSON_PROP_OPERATIONTIMES = "operationTimes";
	public static final String JSON_PROP_UNIQUEKEY = "uniqueKey";
	public static final String JSON_PROP_CATEGORY = "category";
	public static final String JSON_PROP_CATEGORYANDTYPE = "categoryAndType";
	public static final String JSON_PROP_SUPPPRICEINFO = "suppPriceInfo";
	public static final String JSON_PROP_TOTALPRICE = "totalPrice";
	public static final String JSON_PROP_ADULT = "Adult";
	public static final String JSON_PROP_CHILD = "Child";
	public static final String JSON_PROP_PARTICIPANTCATEGORY = "participantCategory";
	public static final String JSON_PROP_SUMMARY = "Summary";
	public static final String JSON_PROP_EXTRA = "extra";
	public static final String JSON_PROP_SUPPLIEROPERATOR = "supplieroperator";
	public static final String JSON_PROP_LOCATION = "location";
	public static final String JSON_PROP_COMMISIONINFO = "commisionInfo";
	public static final String JSON_PROP_PICKUPDROPOFF = "pickupDropOff";
	public static final String JSON_PROP_MEETINGLOCATION = "meetingLocation";
	public static final String JSON_PROP_PICKUPIND = "pickupInd";
	public static final String JSON_PROP_OTHERINFO = "otherInfo";
	public static final String JSON_PROP_STATEPROV = "stateProv";
	public static final String JSON_PROP_ADDRESSLINE="addressLine";
	public static final String JSON_PROP_CODE = "code";
	public static final String JSON_PROP_LANGUAGELISTCODE="languageListCode";
	public static final String JSON_PROP_VALUE = "value";
	public static final String JSON_PROP_SUPPLIER_DETAILS="supplier_Details";
	public static final String JSON_PROP_LONGITUDE="longitude";
	public static final String JSON_PROP_LATITUDE="latitude";
	public static final String JSON_PROP_POSITION="position";
	public static final String JSON_PROP_PARTICIPANT_INFO = "participantInfo";
	public static final String JSON_PROP_NAME_PREFIX = "namePrefix";
	public static final String JSON_PROP_PARTICIPANT_CATEGORY_ID = "participantCategoryID";
	public static final String JSON_PROP_END = "end";
	public static final String JSON_PROP_START = "start";
	public static final String JSON_PROP_NAME_TITLE = "nameTitle";
	public static final String JSON_PROP_SURNAME = "surname";
	public static final String JSON_PROP_MIDDLE_NAME = "middleName";
	public static final String JSON_PROP_GIVEN_NAME = "givenName";
	public static final String JSON_PROP_STATUS = "status";
	public static final String JSON_PROP_CONFIRMATION = "confirmation";
	public static final String JSON_PROP_TIME_SLOT_DETAILS = "timeSlotDetails";
	public static final String JSON_PROP_PHONE_NUMBER = "phoneNumber";
	public static final String JSON_PROP_TELEPHONE = "telephone";
	public static final String JSON_PROP_TOTAL_PRICE_INFO = "totalPriceInfo";
	public static final String JSON_PROP_BLDG_ROOM = "bldgRoom";
	public static final String JSON_PROP_ISO_CURRENCY = "ISOCurrency";
	public static final String JSON_PROP_POS = "POS";
	public static final String JSON_PROP_COMMERCIAL_HEAD_NAME = "commercialHeadName";
	public static final String JSON_PROP_COMMERCIAL_HEAD = "commercialHead";
	public static final String JSON_PROP_ENTITY_DETAILS = "entityDetails";
	public static final String JSON_PROP_TOTAL_FARE = "totalFare";
	public static final String JSON_PROP_COMMERCIAL_DETAILS = "commercialDetails";
	public static final String JSON_PROP_CCE_ACTIVITY_DETAILS = "activityDetails";
	public static final String JSON_PROP_CCE_PRICING = "pricingDetails";
	public static final String JSON_PROP_BUSINESS_RULE_INTAKE = "businessRuleIntake";
	public static final String JSON_PROP_CCE_FAREBREAKUP = "fareBreakup";
	public static final String JSON_PROP_PRICE_BREAKUP = "priceBreakup";
	public static final String JSON_PROP_CONTRACT_VALIDITY = "contractValidity";
	public static final String JSON_PROP_SUPPLIER_MARKET = "supplierMarket";
	public static final String JSON_PROP_SUPPLIER_NAME = "supplierName";
	public static final String JSON_PROP_OPERATION_NAME = "operationName";
	public static final String JSON_PROP_CLIENTCONTEXT = "clientContext";
	public static final String JSON_PROP_CLIENTMARKET = "clientMarket";
	public static final String JSON_PROP_CLIENTCCY = "clientCurrency";
	
	public static final String JSON_PROP_CLIENTCOMMENTITYDTLS ="clientCommercialsEntityDetails";
	public static final String JSON_PROP_COMMENTITYID = "commercialEntityID";
	public static final String JSON_PROP_CLIENTID = "clientID";	
	public static final String JSON_PROP_PARENTCLIENTID = "parentClientID";
	public static final String JSON_PROP_COMMENTITYTYPE = "commercialEntityType";
	public static final String JSON_PROP_COMMERCIALCURRENCY = "commercialCurrency";
	public static final String COMM_TYPE_RECEIVABLE = "Receivable";
	public static final String JSON_PROP_COMMTYPE = "commercialType";
	
	public static final String XPATH_REQUESTHEADER_USERID = "./sig1:RequestHeader/com:UserID";
	public static final String XPATH_REQUESTHEADER_TRANSACTIONID = "./sig1:RequestHeader/com:TransactionID";
	public static final String XPATH_REQUESTHEADER_SESSIONID = "./sig1:RequestHeader/com:SessionID";
	public static final String XPATH_REQUESTHEADER_SUPPLIERCREDENTIALSLIST = "./sig1:RequestHeader/com:SupplierCredentialsList";
	public static final String XPATH_SUPPLIERCREDENTIALS_CREDENTIALSNAME = "./sig1:RequestHeader/com:SupplierCredentialsList/com:SupplierCredentials/com:Credentials/@name";

	
	public static final String ERROR_MSG_NULL_RESPONSE_SI = "Null response received from SI";
	public static final String STATUS_ERROR = "{\"status\": \"ERROR\"}";
	
	
	
	
}
